### ISSUE TITLE
Težave s cookiji

### ISSUE THREAD

**Issue by MocnikS** [SandraKersevan/Pasja-bolha#3]
Zadnja naložena datoteka vsebuje cookije, ki nam iz neznanega razloga ne delujejo.
Želimo si shraniti uporabniško ime človeka, ki se je pravkar prijavil. Težava je v tem, da ko nastavimo `set_cookie` in potem na drugi strani uporabimo `get_cookie`, nam ta vedno vrne None. Poskusile smo tudi z globalno spremenljivko, a tudi ta ne deluje.

**Comment by inesmersak** [comment]
Problem je v redirectu, ki naredi nov HTTP response object in s tem "pozabi" vse cookieje, ki ste jih definirale na response objectu še pred redirectom.

To je baje želeno obnašanje redirecta, ki pa veliko ljudem (tako kot vam) povzroča preglavice ravno pri loginu. Sodeč po [temu issueju](https://github.com/bottlepy/bottle/issues/386) neke lepe rešitve za to ni na voljo (commita, kjer je developer fixal ta issue, zaradi nekega razloga ni več na repozitoriju). 

Workaround: namesto, da "povozimo" response z redirectom, kar trenutni response spremenimo tako, da bo redirect (status code mora biti 303, nastavljen mora biti Location header). 
Namesto vrstice
https://github.com/SandraKersevan/Pasja-bolha/blob/cdabb71795172a666583553f8867d459e904b3d6/pasja_bolha.py#L137
torej dodajte:
```python
response.status = 303
response.set_header('Location', '/oglasi/')
break
```
